"""
ShadowNet — Scenario Data Registry
═══════════════════════════════════════════════════════════════
Combines all 15 scenarios (5 easy, 5 medium, 5 hard).
Maps task names to scenario lists for the environment.
═══════════════════════════════════════════════════════════════
"""

from typing import Dict, List
import random
from models import Scenario, NodeDef, EdgeDef, AttackerStep

# ─── EASY SCENARIOS ─────────────────────────────────────────────────────────
EASY_SCENARIOS = [
    Scenario(
        id="shadow-easy-1", name="Retail POS Breach", difficulty="easy",
        description="Attacker probes web frontend, escalates to auth, pivots to internal API, targets user database. Based on Target 2013 POS breach pattern.",
        max_steps=20, honeypot_fidelity_start=0.85, critical_asset="user-database",
        attack_source="Target 2013 POS Breach",
        nodes=[
            NodeDef(name="web-frontend", sensitivity=2, x=100, y=250,
                    artifacts=["http_access_logs", "waf_alerts"],
                    artifact_decay={"http_access_logs": 8, "waf_alerts": 12}),
            NodeDef(name="auth-service", sensitivity=7, x=280, y=120,
                    artifacts=["auth_tokens", "failed_login_logs"],
                    artifact_decay={"auth_tokens": 4, "failed_login_logs": 10}),
            NodeDef(name="internal-api", sensitivity=6, x=280, y=380,
                    artifacts=["api_call_logs", "session_traces"],
                    artifact_decay={"api_call_logs": 6, "session_traces": 5}),
            NodeDef(name="user-database", sensitivity=9, x=460, y=250,
                    artifacts=["query_logs", "memory_snapshot", "db_transaction_log"],
                    artifact_decay={"query_logs": 7, "memory_snapshot": 3, "db_transaction_log": 9}),
            NodeDef(name="logging-service", sensitivity=3, x=100, y=450,
                    artifacts=["syslog_archive"],
                    artifact_decay={"syslog_archive": 15}),
        ],
        edges=[
            EdgeDef(source="web-frontend", target="auth-service"),
            EdgeDef(source="web-frontend", target="internal-api"),
            EdgeDef(source="auth-service", target="user-database"),
            EdgeDef(source="internal-api", target="user-database"),
            EdgeDef(source="web-frontend", target="logging-service"),
        ],
        attacker_path=[
            AttackerStep(step=1, action="probe", target="web-frontend"),
            AttackerStep(step=3, action="escalate", target="auth-service"),
            AttackerStep(step=6, action="pivot", target="internal-api"),
            AttackerStep(step=9, action="exfiltrate", target="user-database"),
        ],
    ),
    Scenario(
        id="shadow-easy-2", name="Credential Stuffing Attack", difficulty="easy",
        description="Attacker uses stolen credentials on login portal, moves to user profiles, attempts data export. Based on common credential stuffing patterns.",
        max_steps=20, honeypot_fidelity_start=0.88, critical_asset="customer-records",
        attack_source="Generic Credential Stuffing",
        nodes=[
            NodeDef(name="login-portal", sensitivity=3, x=100, y=250,
                    artifacts=["login_attempt_logs", "ip_geolocation_data"],
                    artifact_decay={"login_attempt_logs": 10, "ip_geolocation_data": 12}),
            NodeDef(name="user-profiles", sensitivity=6, x=280, y=150,
                    artifacts=["profile_access_logs", "session_cookies"],
                    artifact_decay={"profile_access_logs": 8, "session_cookies": 3}),
            NodeDef(name="customer-records", sensitivity=9, x=460, y=150,
                    artifacts=["export_queue_logs", "memory_snapshot"],
                    artifact_decay={"export_queue_logs": 6, "memory_snapshot": 3}),
            NodeDef(name="email-service", sensitivity=4, x=280, y=380,
                    artifacts=["smtp_logs"],
                    artifact_decay={"smtp_logs": 14}),
            NodeDef(name="cdn-cache", sensitivity=2, x=460, y=380,
                    artifacts=["cache_hit_logs"],
                    artifact_decay={"cache_hit_logs": 16}),
        ],
        edges=[
            EdgeDef(source="login-portal", target="user-profiles"),
            EdgeDef(source="login-portal", target="email-service"),
            EdgeDef(source="user-profiles", target="customer-records"),
            EdgeDef(source="email-service", target="cdn-cache"),
            EdgeDef(source="user-profiles", target="cdn-cache"),
        ],
        attacker_path=[
            AttackerStep(step=1, action="probe", target="login-portal"),
            AttackerStep(step=4, action="escalate", target="user-profiles"),
            AttackerStep(step=7, action="pivot", target="email-service"),
            AttackerStep(step=10, action="exfiltrate", target="customer-records"),
        ],
    ),
    Scenario(
        id="shadow-easy-3", name="SSH Brute Force Intrusion", difficulty="easy",
        description="Attacker brute-forces SSH on jump server, pivots to dev environment, targets source code repo. Based on common SSH attack chains.",
        max_steps=20, honeypot_fidelity_start=0.85, critical_asset="source-repo",
        attack_source="SSH Brute Force Pattern",
        nodes=[
            NodeDef(name="jump-server", sensitivity=4, x=100, y=250,
                    artifacts=["ssh_auth_logs", "connection_metadata"],
                    artifact_decay={"ssh_auth_logs": 10, "connection_metadata": 8}),
            NodeDef(name="dev-workstation", sensitivity=5, x=280, y=150,
                    artifacts=["bash_history", "process_list"],
                    artifact_decay={"bash_history": 6, "process_list": 4}),
            NodeDef(name="source-repo", sensitivity=9, x=460, y=150,
                    artifacts=["git_logs", "access_tokens", "memory_snapshot"],
                    artifact_decay={"git_logs": 12, "access_tokens": 3, "memory_snapshot": 3}),
            NodeDef(name="ci-runner", sensitivity=3, x=280, y=380,
                    artifacts=["build_logs"],
                    artifact_decay={"build_logs": 14}),
            NodeDef(name="monitoring", sensitivity=2, x=460, y=380,
                    artifacts=["metric_exports"],
                    artifact_decay={"metric_exports": 16}),
        ],
        edges=[
            EdgeDef(source="jump-server", target="dev-workstation"),
            EdgeDef(source="jump-server", target="ci-runner"),
            EdgeDef(source="dev-workstation", target="source-repo"),
            EdgeDef(source="ci-runner", target="source-repo"),
            EdgeDef(source="ci-runner", target="monitoring"),
        ],
        attacker_path=[
            AttackerStep(step=2, action="probe", target="jump-server"),
            AttackerStep(step=5, action="escalate", target="dev-workstation"),
            AttackerStep(step=8, action="pivot", target="ci-runner"),
            AttackerStep(step=11, action="exfiltrate", target="source-repo"),
        ],
    ),
    Scenario(
        id="shadow-easy-4", name="Phishing to Mailbox Exfil", difficulty="easy",
        description="Attacker phishes employee, accesses mailbox, searches for sensitive attachments, exfiltrates via cloud sync. Based on BEC attack patterns.",
        max_steps=20, honeypot_fidelity_start=0.87, critical_asset="cloud-storage",
        attack_source="Business Email Compromise",
        nodes=[
            NodeDef(name="employee-endpoint", sensitivity=3, x=100, y=250,
                    artifacts=["endpoint_telemetry", "browser_history"],
                    artifact_decay={"endpoint_telemetry": 8, "browser_history": 5}),
            NodeDef(name="exchange-server", sensitivity=6, x=280, y=150,
                    artifacts=["mailbox_audit_log", "attachment_hashes"],
                    artifact_decay={"mailbox_audit_log": 10, "attachment_hashes": 7}),
            NodeDef(name="sharepoint", sensitivity=5, x=280, y=380,
                    artifacts=["file_access_logs"],
                    artifact_decay={"file_access_logs": 9}),
            NodeDef(name="cloud-storage", sensitivity=9, x=460, y=250,
                    artifacts=["sync_logs", "memory_snapshot", "api_tokens"],
                    artifact_decay={"sync_logs": 6, "memory_snapshot": 3, "api_tokens": 4}),
            NodeDef(name="dlp-gateway", sensitivity=2, x=100, y=450,
                    artifacts=["dlp_alerts"],
                    artifact_decay={"dlp_alerts": 15}),
        ],
        edges=[
            EdgeDef(source="employee-endpoint", target="exchange-server"),
            EdgeDef(source="employee-endpoint", target="sharepoint"),
            EdgeDef(source="exchange-server", target="cloud-storage"),
            EdgeDef(source="sharepoint", target="cloud-storage"),
            EdgeDef(source="employee-endpoint", target="dlp-gateway"),
        ],
        attacker_path=[
            AttackerStep(step=1, action="probe", target="employee-endpoint"),
            AttackerStep(step=3, action="escalate", target="exchange-server"),
            AttackerStep(step=6, action="pivot", target="sharepoint"),
            AttackerStep(step=9, action="exfiltrate", target="cloud-storage"),
        ],
    ),
    Scenario(
        id="shadow-easy-5", name="DNS Tunneling Exfil", difficulty="easy",
        description="Attacker establishes DNS tunnel from compromised workstation, moves to internal DNS server, exfiltrates through encoded DNS queries. Based on DNSCat2 attack patterns.",
        max_steps=20, honeypot_fidelity_start=0.86, critical_asset="hr-database",
        attack_source="DNS Tunneling via DNSCat2",
        nodes=[
            NodeDef(name="workstation-42", sensitivity=3, x=100, y=250,
                    artifacts=["dns_query_logs", "process_memory"],
                    artifact_decay={"dns_query_logs": 10, "process_memory": 3}),
            NodeDef(name="internal-dns", sensitivity=5, x=280, y=150,
                    artifacts=["dns_cache_dump", "query_frequency_data"],
                    artifact_decay={"dns_cache_dump": 6, "query_frequency_data": 8}),
            NodeDef(name="hr-database", sensitivity=9, x=460, y=150,
                    artifacts=["db_audit_log", "memory_snapshot", "network_pcap"],
                    artifact_decay={"db_audit_log": 9, "memory_snapshot": 3, "network_pcap": 5}),
            NodeDef(name="proxy-server", sensitivity=4, x=280, y=380,
                    artifacts=["proxy_access_logs"],
                    artifact_decay={"proxy_access_logs": 12}),
            NodeDef(name="firewall", sensitivity=2, x=460, y=380,
                    artifacts=["firewall_session_logs"],
                    artifact_decay={"firewall_session_logs": 15}),
        ],
        edges=[
            EdgeDef(source="workstation-42", target="internal-dns"),
            EdgeDef(source="workstation-42", target="proxy-server"),
            EdgeDef(source="internal-dns", target="hr-database"),
            EdgeDef(source="proxy-server", target="hr-database"),
            EdgeDef(source="proxy-server", target="firewall"),
        ],
        attacker_path=[
            AttackerStep(step=2, action="probe", target="workstation-42"),
            AttackerStep(step=4, action="escalate", target="internal-dns"),
            AttackerStep(step=7, action="pivot", target="proxy-server"),
            AttackerStep(step=10, action="exfiltrate", target="hr-database"),
        ],
    ),
]

# ─── MEDIUM SCENARIOS ───────────────────────────────────────────────────────
MEDIUM_SCENARIOS = [
    Scenario(
        id="shadow-medium-1", name="Uber Social Engineering", difficulty="medium",
        description="Attacker social-engineers employee via Slack, pivots through VPN to internal tools, targets admin panel and payment data. Based on Uber 2022 breach.",
        max_steps=16, honeypot_fidelity_start=0.82, critical_asset="payment-processor",
        attack_source="Uber 2022 Social Engineering Breach",
        nodes=[
            NodeDef(name="slack-workspace", sensitivity=3, x=80, y=200,
                    artifacts=["message_logs", "oauth_tokens"],
                    artifact_decay={"message_logs": 8, "oauth_tokens": 3}),
            NodeDef(name="vpn-gateway", sensitivity=5, x=200, y=80,
                    artifacts=["vpn_session_logs", "mfa_bypass_evidence"],
                    artifact_decay={"vpn_session_logs": 7, "mfa_bypass_evidence": 4}),
            NodeDef(name="internal-wiki", sensitivity=4, x=200, y=320,
                    artifacts=["page_access_logs"],
                    artifact_decay={"page_access_logs": 10}),
            NodeDef(name="admin-panel", sensitivity=8, x=350, y=80,
                    artifacts=["admin_audit_log", "privilege_escalation_trace"],
                    artifact_decay={"admin_audit_log": 6, "privilege_escalation_trace": 4}),
            NodeDef(name="cloud-console", sensitivity=7, x=350, y=200,
                    artifacts=["iam_change_log", "api_key_usage"],
                    artifact_decay={"iam_change_log": 5, "api_key_usage": 4}),
            NodeDef(name="payment-processor", sensitivity=10, x=500, y=80,
                    artifacts=["transaction_logs", "memory_snapshot", "pci_audit_trail"],
                    artifact_decay={"transaction_logs": 8, "memory_snapshot": 3, "pci_audit_trail": 6}),
            NodeDef(name="user-database", sensitivity=9, x=500, y=320,
                    artifacts=["query_logs", "schema_dump"],
                    artifact_decay={"query_logs": 7, "schema_dump": 5}),
            NodeDef(name="logging-service", sensitivity=2, x=80, y=400,
                    artifacts=["centralized_syslog"],
                    artifact_decay={"centralized_syslog": 14}),
        ],
        edges=[
            EdgeDef(source="slack-workspace", target="vpn-gateway"),
            EdgeDef(source="slack-workspace", target="internal-wiki"),
            EdgeDef(source="vpn-gateway", target="admin-panel"),
            EdgeDef(source="vpn-gateway", target="cloud-console"),
            EdgeDef(source="internal-wiki", target="cloud-console"),
            EdgeDef(source="admin-panel", target="payment-processor"),
            EdgeDef(source="cloud-console", target="user-database"),
            EdgeDef(source="slack-workspace", target="logging-service"),
        ],
        attacker_path=[
            AttackerStep(step=1, action="probe", target="slack-workspace"),
            AttackerStep(step=2, action="escalate", target="vpn-gateway"),
            AttackerStep(step=4, action="lateral", target="internal-wiki"),  # DECOY — wastes agent attention
            AttackerStep(step=5, action="pivot", target="admin-panel"),
            AttackerStep(step=7, action="escalate", target="cloud-console"),
            AttackerStep(step=9, action="exfiltrate", target="payment-processor"),
        ],
    ),
    Scenario(
        id="shadow-medium-2", name="Supply Chain Backdoor", difficulty="medium",
        description="Attacker compromises a CI/CD pipeline dependency, backdoor triggers on build, spreads to staging then production. Based on SolarWinds Orion pattern (simplified).",
        max_steps=16, honeypot_fidelity_start=0.80, critical_asset="production-api",
        attack_source="SolarWinds 2020 (simplified)",
        nodes=[
            NodeDef(name="package-registry", sensitivity=4, x=80, y=200,
                    artifacts=["package_checksums", "download_logs"],
                    artifact_decay={"package_checksums": 10, "download_logs": 8}),
            NodeDef(name="ci-pipeline", sensitivity=6, x=200, y=100,
                    artifacts=["build_logs", "artifact_hashes"],
                    artifact_decay={"build_logs": 7, "artifact_hashes": 5}),
            NodeDef(name="staging-env", sensitivity=5, x=350, y=100,
                    artifacts=["deployment_logs", "config_snapshots"],
                    artifact_decay={"deployment_logs": 6, "config_snapshots": 4}),
            NodeDef(name="production-api", sensitivity=10, x=500, y=200,
                    artifacts=["request_logs", "memory_dump", "ssl_session_keys"],
                    artifact_decay={"request_logs": 8, "memory_dump": 3, "ssl_session_keys": 3}),
            NodeDef(name="secrets-vault", sensitivity=9, x=350, y=320,
                    artifacts=["vault_audit_log", "key_rotation_history"],
                    artifact_decay={"vault_audit_log": 5, "key_rotation_history": 7}),
            NodeDef(name="developer-laptop", sensitivity=3, x=200, y=320,
                    artifacts=["git_commit_history"],
                    artifact_decay={"git_commit_history": 12}),
            NodeDef(name="test-database", sensitivity=4, x=500, y=380,
                    artifacts=["test_data_exports"],
                    artifact_decay={"test_data_exports": 10}),
            NodeDef(name="slack-alerts", sensitivity=1, x=80, y=400,
                    artifacts=["notification_logs"],
                    artifact_decay={"notification_logs": 15}),
        ],
        edges=[
            EdgeDef(source="package-registry", target="ci-pipeline"),
            EdgeDef(source="ci-pipeline", target="staging-env"),
            EdgeDef(source="staging-env", target="production-api"),
            EdgeDef(source="ci-pipeline", target="secrets-vault"),
            EdgeDef(source="package-registry", target="developer-laptop"),
            EdgeDef(source="developer-laptop", target="test-database"),  # DECOY path
            EdgeDef(source="production-api", target="test-database"),
            EdgeDef(source="package-registry", target="slack-alerts"),
        ],
        attacker_path=[
            AttackerStep(step=1, action="probe", target="package-registry"),
            AttackerStep(step=2, action="persist", target="ci-pipeline"),
            AttackerStep(step=3, action="lateral", target="developer-laptop"),  # DECOY
            AttackerStep(step=5, action="pivot", target="staging-env"),
            AttackerStep(step=7, action="escalate", target="secrets-vault"),
            AttackerStep(step=9, action="exfiltrate", target="production-api"),
        ],
    ),
    Scenario(
        id="shadow-medium-3", name="Healthcare Records Theft", difficulty="medium",
        description="Attacker exploits patient portal vulnerability, moves to EHR system, targets medical records database. Based on Anthem 2015 breach pattern.",
        max_steps=16, honeypot_fidelity_start=0.83, critical_asset="medical-records-db",
        attack_source="Anthem 2015 Healthcare Breach",
        nodes=[
            NodeDef(name="patient-portal", sensitivity=4, x=80, y=200,
                    artifacts=["web_access_logs", "session_tokens"],
                    artifact_decay={"web_access_logs": 9, "session_tokens": 3}),
            NodeDef(name="ehr-application", sensitivity=7, x=200, y=100,
                    artifacts=["ehr_audit_trail", "api_call_logs"],
                    artifact_decay={"ehr_audit_trail": 6, "api_call_logs": 5}),
            NodeDef(name="medical-records-db", sensitivity=10, x=400, y=100,
                    artifacts=["query_logs", "memory_snapshot", "phi_access_log"],
                    artifact_decay={"query_logs": 7, "memory_snapshot": 3, "phi_access_log": 5}),
            NodeDef(name="billing-system", sensitivity=6, x=200, y=320,
                    artifacts=["billing_transaction_log"],
                    artifact_decay={"billing_transaction_log": 8}),
            NodeDef(name="lab-results", sensitivity=5, x=400, y=320,
                    artifacts=["lab_access_log"],
                    artifact_decay={"lab_access_log": 10}),
            NodeDef(name="pharmacy-api", sensitivity=6, x=550, y=200,
                    artifacts=["prescription_logs", "dea_audit"],
                    artifact_decay={"prescription_logs": 7, "dea_audit": 9}),
            NodeDef(name="insurance-gateway", sensitivity=5, x=550, y=380,
                    artifacts=["claims_data_log"],
                    artifact_decay={"claims_data_log": 11}),
            NodeDef(name="backup-server", sensitivity=3, x=80, y=400,
                    artifacts=["backup_manifests"],
                    artifact_decay={"backup_manifests": 14}),
        ],
        edges=[
            EdgeDef(source="patient-portal", target="ehr-application"),
            EdgeDef(source="patient-portal", target="billing-system"),
            EdgeDef(source="ehr-application", target="medical-records-db"),
            EdgeDef(source="ehr-application", target="pharmacy-api"),
            EdgeDef(source="billing-system", target="lab-results"),  # DECOY
            EdgeDef(source="billing-system", target="insurance-gateway"),
            EdgeDef(source="medical-records-db", target="pharmacy-api"),
            EdgeDef(source="patient-portal", target="backup-server"),
        ],
        attacker_path=[
            AttackerStep(step=1, action="probe", target="patient-portal"),
            AttackerStep(step=2, action="escalate", target="ehr-application"),
            AttackerStep(step=4, action="lateral", target="billing-system"),  # DECOY
            AttackerStep(step=6, action="pivot", target="pharmacy-api"),
            AttackerStep(step=8, action="exfiltrate", target="medical-records-db"),
        ],
    ),
    Scenario(
        id="shadow-medium-4", name="Cloud IAM Escalation", difficulty="medium",
        description="Attacker steals AWS access key from exposed .env file, escalates IAM privileges, pivots to S3 buckets with sensitive data. Based on Capital One 2019 pattern.",
        max_steps=16, honeypot_fidelity_start=0.81, critical_asset="s3-data-lake",
        attack_source="Capital One 2019 SSRF + IAM Escalation",
        nodes=[
            NodeDef(name="public-ec2", sensitivity=3, x=80, y=200,
                    artifacts=["cloudtrail_logs", "instance_metadata"],
                    artifact_decay={"cloudtrail_logs": 9, "instance_metadata": 4}),
            NodeDef(name="iam-service", sensitivity=8, x=200, y=100,
                    artifacts=["iam_policy_changes", "role_assumption_log"],
                    artifact_decay={"iam_policy_changes": 5, "role_assumption_log": 4}),
            NodeDef(name="lambda-functions", sensitivity=5, x=350, y=100,
                    artifacts=["invocation_logs", "env_variables_snapshot"],
                    artifact_decay={"invocation_logs": 7, "env_variables_snapshot": 3}),
            NodeDef(name="s3-data-lake", sensitivity=10, x=500, y=200,
                    artifacts=["access_logs", "object_listing", "memory_snapshot"],
                    artifact_decay={"access_logs": 8, "object_listing": 5, "memory_snapshot": 3}),
            NodeDef(name="rds-database", sensitivity=7, x=350, y=320,
                    artifacts=["slow_query_log", "connection_logs"],
                    artifact_decay={"slow_query_log": 6, "connection_logs": 8}),
            NodeDef(name="cloudwatch", sensitivity=2, x=200, y=320,
                    artifacts=["metric_exports"],
                    artifact_decay={"metric_exports": 14}),
            NodeDef(name="sns-queue", sensitivity=2, x=500, y=380,
                    artifacts=["message_logs"],
                    artifact_decay={"message_logs": 12}),
            NodeDef(name="vpc-flowlogs", sensitivity=1, x=80, y=400,
                    artifacts=["network_flow_data"],
                    artifact_decay={"network_flow_data": 15}),
        ],
        edges=[
            EdgeDef(source="public-ec2", target="iam-service"),
            EdgeDef(source="iam-service", target="lambda-functions"),
            EdgeDef(source="iam-service", target="s3-data-lake"),
            EdgeDef(source="lambda-functions", target="rds-database"),
            EdgeDef(source="public-ec2", target="cloudwatch"),
            EdgeDef(source="lambda-functions", target="sns-queue"),  # DECOY
            EdgeDef(source="rds-database", target="s3-data-lake"),
            EdgeDef(source="public-ec2", target="vpc-flowlogs"),
        ],
        attacker_path=[
            AttackerStep(step=1, action="probe", target="public-ec2"),
            AttackerStep(step=2, action="escalate", target="iam-service"),
            AttackerStep(step=4, action="lateral", target="lambda-functions"),
            AttackerStep(step=5, action="pivot", target="rds-database"),  # DECOY
            AttackerStep(step=7, action="escalate", target="s3-data-lake"),
        ],
    ),
    Scenario(
        id="shadow-medium-5", name="Ransomware Lateral Spread", difficulty="medium",
        description="Attacker deploys ransomware via compromised RDP, spreads laterally through SMB shares, targets domain controller. Based on Ryuk ransomware campaigns.",
        max_steps=16, honeypot_fidelity_start=0.80, critical_asset="domain-controller",
        attack_source="Ryuk Ransomware Campaign Pattern",
        nodes=[
            NodeDef(name="rdp-server", sensitivity=4, x=80, y=200,
                    artifacts=["rdp_session_logs", "credential_cache"],
                    artifact_decay={"rdp_session_logs": 8, "credential_cache": 3}),
            NodeDef(name="file-share-01", sensitivity=5, x=200, y=100,
                    artifacts=["smb_access_logs", "file_modification_timeline"],
                    artifact_decay={"smb_access_logs": 7, "file_modification_timeline": 5}),
            NodeDef(name="file-share-02", sensitivity=5, x=200, y=320,
                    artifacts=["smb_access_logs", "encryption_indicators"],
                    artifact_decay={"smb_access_logs": 7, "encryption_indicators": 4}),
            NodeDef(name="exchange-server", sensitivity=7, x=350, y=200,
                    artifacts=["mailbox_audit", "transport_logs"],
                    artifact_decay={"mailbox_audit": 6, "transport_logs": 8}),
            NodeDef(name="domain-controller", sensitivity=10, x=500, y=200,
                    artifacts=["ad_replication_log", "memory_dump", "gpo_change_log"],
                    artifact_decay={"ad_replication_log": 5, "memory_dump": 3, "gpo_change_log": 6}),
            NodeDef(name="backup-server", sensitivity=8, x=500, y=380,
                    artifacts=["backup_job_logs", "vss_snapshot_status"],
                    artifact_decay={"backup_job_logs": 7, "vss_snapshot_status": 4}),
            NodeDef(name="print-server", sensitivity=1, x=350, y=400,
                    artifacts=["print_queue_logs"],
                    artifact_decay={"print_queue_logs": 15}),
            NodeDef(name="siem-collector", sensitivity=2, x=80, y=400,
                    artifacts=["aggregated_alerts"],
                    artifact_decay={"aggregated_alerts": 14}),
        ],
        edges=[
            EdgeDef(source="rdp-server", target="file-share-01"),
            EdgeDef(source="rdp-server", target="file-share-02"),
            EdgeDef(source="file-share-01", target="exchange-server"),
            EdgeDef(source="file-share-02", target="print-server"),  # DECOY
            EdgeDef(source="exchange-server", target="domain-controller"),
            EdgeDef(source="domain-controller", target="backup-server"),
            EdgeDef(source="file-share-01", target="domain-controller"),
            EdgeDef(source="rdp-server", target="siem-collector"),
        ],
        attacker_path=[
            AttackerStep(step=1, action="probe", target="rdp-server"),
            AttackerStep(step=2, action="lateral", target="file-share-01"),
            AttackerStep(step=3, action="lateral", target="file-share-02"),  # DECOY
            AttackerStep(step=5, action="pivot", target="exchange-server"),
            AttackerStep(step=7, action="escalate", target="domain-controller"),
            AttackerStep(step=9, action="exfiltrate", target="backup-server"),
        ],
    ),
]

# ─── HARD SCENARIOS ─────────────────────────────────────────────────────────
HARD_SCENARIOS = [
    Scenario(
        id="shadow-hard-1", name="SolarWinds APT Campaign", difficulty="hard",
        description="Nation-state attacker inside Orion build system. Multiple lateral paths, fast movement, single critical target: the update distribution server. Based on SolarWinds 2020 APT29.",
        max_steps=12, honeypot_fidelity_start=0.75, critical_asset="update-distribution",
        attack_source="SolarWinds 2020 APT29 (SUNBURST)",
        nodes=[
            NodeDef(name="orion-build", sensitivity=6, x=80, y=200, artifacts=["build_checksums", "compiler_logs"], artifact_decay={"build_checksums": 5, "compiler_logs": 4}),
            NodeDef(name="source-control", sensitivity=7, x=180, y=80, artifacts=["commit_signatures", "merge_audit"], artifact_decay={"commit_signatures": 4, "merge_audit": 3}),
            NodeDef(name="code-signing", sensitivity=9, x=300, y=80, artifacts=["signing_key_usage", "certificate_log"], artifact_decay={"signing_key_usage": 3, "certificate_log": 4}),
            NodeDef(name="test-farm", sensitivity=3, x=180, y=320, artifacts=["test_results"], artifact_decay={"test_results": 8}),
            NodeDef(name="staging-mirror", sensitivity=5, x=300, y=200, artifacts=["deployment_manifest", "hash_comparison"], artifact_decay={"deployment_manifest": 4, "hash_comparison": 3}),
            NodeDef(name="update-distribution", sensitivity=10, x=450, y=80, artifacts=["distribution_logs", "memory_dump", "customer_pull_records"], artifact_decay={"distribution_logs": 5, "memory_dump": 2, "customer_pull_records": 4}),
            NodeDef(name="telemetry-server", sensitivity=4, x=450, y=200, artifacts=["beacon_logs"], artifact_decay={"beacon_logs": 6}),
            NodeDef(name="internal-dns", sensitivity=3, x=450, y=320, artifacts=["dns_query_log"], artifact_decay={"dns_query_log": 7}),
            NodeDef(name="vpn-concentrator", sensitivity=5, x=580, y=80, artifacts=["vpn_session_data"], artifact_decay={"vpn_session_data": 5}),
            NodeDef(name="ad-forest", sensitivity=8, x=580, y=200, artifacts=["kerberos_tickets", "ad_replication"], artifact_decay={"kerberos_tickets": 3, "ad_replication": 4}),
            NodeDef(name="email-server", sensitivity=4, x=580, y=320, artifacts=["email_headers"], artifact_decay={"email_headers": 6}),
            NodeDef(name="soc-dashboard", sensitivity=2, x=80, y=400, artifacts=["alert_history"], artifact_decay={"alert_history": 10}),
        ],
        edges=[
            EdgeDef(source="orion-build", target="source-control"),
            EdgeDef(source="orion-build", target="test-farm"),
            EdgeDef(source="source-control", target="code-signing"),
            EdgeDef(source="code-signing", target="update-distribution"),
            EdgeDef(source="orion-build", target="staging-mirror"),
            EdgeDef(source="staging-mirror", target="update-distribution"),
            EdgeDef(source="staging-mirror", target="telemetry-server"),
            EdgeDef(source="telemetry-server", target="internal-dns"),
            EdgeDef(source="update-distribution", target="vpn-concentrator"),
            EdgeDef(source="vpn-concentrator", target="ad-forest"),
            EdgeDef(source="ad-forest", target="email-server"),
            EdgeDef(source="orion-build", target="soc-dashboard"),
        ],
        attacker_path=[
            AttackerStep(step=1, action="persist", target="orion-build"),
            AttackerStep(step=2, action="escalate", target="source-control"),
            AttackerStep(step=3, action="lateral", target="test-farm"),
            AttackerStep(step=4, action="pivot", target="code-signing"),
            AttackerStep(step=5, action="lateral", target="staging-mirror"),
            AttackerStep(step=6, action="pivot", target="telemetry-server"),
            AttackerStep(step=8, action="exfiltrate", target="update-distribution"),
            AttackerStep(step=9, action="lateral", target="ad-forest"),
        ],
    ),
    Scenario(
        id="shadow-hard-2", name="Colonial Pipeline OT Attack", difficulty="hard",
        description="Attacker enters through IT network, crosses IT/OT boundary to reach SCADA controllers. One wrong move exposes pipeline operations. Based on Colonial Pipeline 2021.",
        max_steps=12, honeypot_fidelity_start=0.76, critical_asset="scada-controller",
        attack_source="Colonial Pipeline 2021 (DarkSide)",
        nodes=[
            NodeDef(name="corporate-vpn", sensitivity=4, x=80, y=150, artifacts=["vpn_auth_logs", "session_metadata"], artifact_decay={"vpn_auth_logs": 5, "session_metadata": 4}),
            NodeDef(name="it-workstation", sensitivity=3, x=80, y=300, artifacts=["endpoint_logs"], artifact_decay={"endpoint_logs": 6}),
            NodeDef(name="active-directory", sensitivity=8, x=200, y=80, artifacts=["ad_event_log", "kerberoast_evidence"], artifact_decay={"ad_event_log": 4, "kerberoast_evidence": 3}),
            NodeDef(name="file-server", sensitivity=5, x=200, y=220, artifacts=["smb_audit_log", "file_access_timeline"], artifact_decay={"smb_audit_log": 5, "file_access_timeline": 4}),
            NodeDef(name="billing-system", sensitivity=7, x=200, y=360, artifacts=["billing_db_log", "api_tokens"], artifact_decay={"billing_db_log": 5, "api_tokens": 3}),
            NodeDef(name="it-ot-gateway", sensitivity=9, x=380, y=200, artifacts=["firewall_rules_snapshot", "crossing_log"], artifact_decay={"firewall_rules_snapshot": 3, "crossing_log": 4}),
            NodeDef(name="historian-db", sensitivity=7, x=500, y=100, artifacts=["process_data_log"], artifact_decay={"process_data_log": 5}),
            NodeDef(name="scada-controller", sensitivity=10, x=620, y=200, artifacts=["plc_command_log", "memory_dump", "safety_system_state"], artifact_decay={"plc_command_log": 4, "memory_dump": 2, "safety_system_state": 3}),
            NodeDef(name="hmi-station", sensitivity=6, x=500, y=300, artifacts=["operator_actions_log"], artifact_decay={"operator_actions_log": 5}),
            NodeDef(name="engineering-ws", sensitivity=5, x=620, y=350, artifacts=["project_files_hash"], artifact_decay={"project_files_hash": 6}),
            NodeDef(name="backup-nas", sensitivity=4, x=380, y=380, artifacts=["backup_integrity_check"], artifact_decay={"backup_integrity_check": 7}),
            NodeDef(name="siem-collector", sensitivity=2, x=80, y=430, artifacts=["correlated_alerts"], artifact_decay={"correlated_alerts": 9}),
        ],
        edges=[
            EdgeDef(source="corporate-vpn", target="active-directory"),
            EdgeDef(source="corporate-vpn", target="it-workstation"),
            EdgeDef(source="it-workstation", target="file-server"),
            EdgeDef(source="active-directory", target="billing-system"),
            EdgeDef(source="file-server", target="it-ot-gateway"),
            EdgeDef(source="active-directory", target="it-ot-gateway"),
            EdgeDef(source="it-ot-gateway", target="historian-db"),
            EdgeDef(source="it-ot-gateway", target="scada-controller"),
            EdgeDef(source="historian-db", target="hmi-station"),
            EdgeDef(source="scada-controller", target="engineering-ws"),
            EdgeDef(source="billing-system", target="backup-nas"),
            EdgeDef(source="corporate-vpn", target="siem-collector"),
        ],
        attacker_path=[
            AttackerStep(step=1, action="probe", target="corporate-vpn"),
            AttackerStep(step=2, action="escalate", target="active-directory"),
            AttackerStep(step=3, action="lateral", target="it-workstation"),
            AttackerStep(step=4, action="pivot", target="file-server"),
            AttackerStep(step=5, action="lateral", target="billing-system"),
            AttackerStep(step=6, action="escalate", target="it-ot-gateway"),
            AttackerStep(step=8, action="pivot", target="historian-db"),
            AttackerStep(step=9, action="exfiltrate", target="scada-controller"),
        ],
    ),
    Scenario(
        id="shadow-hard-3", name="Exchange Zero-Day (ProxyLogon)", difficulty="hard",
        description="Attacker exploits Exchange zero-day, dumps mailboxes, uses NTLM relay to reach domain controller, targets certificate authority. Based on Hafnium/ProxyLogon 2021.",
        max_steps=12, honeypot_fidelity_start=0.74, critical_asset="certificate-authority",
        attack_source="Hafnium ProxyLogon 2021",
        nodes=[
            NodeDef(name="exchange-cas", sensitivity=7, x=80, y=200, artifacts=["iis_logs", "owa_auth_logs"], artifact_decay={"iis_logs": 5, "owa_auth_logs": 4}),
            NodeDef(name="exchange-mailbox", sensitivity=6, x=200, y=80, artifacts=["mailbox_export_log", "webshell_artifacts"], artifact_decay={"mailbox_export_log": 4, "webshell_artifacts": 3}),
            NodeDef(name="exchange-transport", sensitivity=5, x=200, y=320, artifacts=["transport_queue_log"], artifact_decay={"transport_queue_log": 6}),
            NodeDef(name="domain-controller", sensitivity=9, x=350, y=80, artifacts=["ntds_dit_hash", "dc_replication_log"], artifact_decay={"ntds_dit_hash": 3, "dc_replication_log": 4}),
            NodeDef(name="certificate-authority", sensitivity=10, x=500, y=80, artifacts=["cert_issuance_log", "private_key_access", "memory_dump"], artifact_decay={"cert_issuance_log": 4, "private_key_access": 2, "memory_dump": 2}),
            NodeDef(name="sql-server", sensitivity=6, x=350, y=200, artifacts=["query_history", "connection_log"], artifact_decay={"query_history": 5, "connection_log": 4}),
            NodeDef(name="sharepoint", sensitivity=5, x=350, y=340, artifacts=["document_access_log"], artifact_decay={"document_access_log": 6}),
            NodeDef(name="adfs-server", sensitivity=8, x=500, y=200, artifacts=["saml_token_log", "federation_metadata"], artifact_decay={"saml_token_log": 3, "federation_metadata": 4}),
            NodeDef(name="azure-ad-connect", sensitivity=7, x=500, y=340, artifacts=["sync_log", "password_hash_sync"], artifact_decay={"sync_log": 4, "password_hash_sync": 3}),
            NodeDef(name="file-server", sensitivity=4, x=620, y=200, artifacts=["smb_access_log"], artifact_decay={"smb_access_log": 6}),
            NodeDef(name="print-server", sensitivity=1, x=620, y=340, artifacts=["spooler_log"], artifact_decay={"spooler_log": 10}),
            NodeDef(name="wef-collector", sensitivity=2, x=80, y=400, artifacts=["forwarded_events"], artifact_decay={"forwarded_events": 9}),
        ],
        edges=[
            EdgeDef(source="exchange-cas", target="exchange-mailbox"),
            EdgeDef(source="exchange-cas", target="exchange-transport"),
            EdgeDef(source="exchange-mailbox", target="domain-controller"),
            EdgeDef(source="exchange-transport", target="sharepoint"),
            EdgeDef(source="domain-controller", target="certificate-authority"),
            EdgeDef(source="domain-controller", target="sql-server"),
            EdgeDef(source="sql-server", target="adfs-server"),
            EdgeDef(source="certificate-authority", target="adfs-server"),
            EdgeDef(source="adfs-server", target="azure-ad-connect"),
            EdgeDef(source="domain-controller", target="file-server"),
            EdgeDef(source="file-server", target="print-server"),
            EdgeDef(source="exchange-cas", target="wef-collector"),
        ],
        attacker_path=[
            AttackerStep(step=1, action="probe", target="exchange-cas"),
            AttackerStep(step=2, action="escalate", target="exchange-mailbox"),
            AttackerStep(step=3, action="lateral", target="exchange-transport"),
            AttackerStep(step=4, action="pivot", target="domain-controller"),
            AttackerStep(step=5, action="lateral", target="sql-server"),
            AttackerStep(step=6, action="escalate", target="adfs-server"),
            AttackerStep(step=7, action="pivot", target="azure-ad-connect"),
            AttackerStep(step=9, action="exfiltrate", target="certificate-authority"),
        ],
    ),
    Scenario(
        id="shadow-hard-4", name="Kubernetes Cluster Takeover", difficulty="hard",
        description="Attacker exploits exposed API server, escapes container, compromises etcd, targets secrets and service mesh. Based on Tesla 2018 k8s breach + modern patterns.",
        max_steps=12, honeypot_fidelity_start=0.73, critical_asset="etcd-cluster",
        attack_source="Tesla 2018 Kubernetes + Modern k8s Attack Chains",
        nodes=[
            NodeDef(name="k8s-api-server", sensitivity=8, x=80, y=200, artifacts=["api_audit_log", "admission_webhooks"], artifact_decay={"api_audit_log": 4, "admission_webhooks": 3}),
            NodeDef(name="worker-node-01", sensitivity=4, x=200, y=80, artifacts=["kubelet_logs", "container_runtime_log"], artifact_decay={"kubelet_logs": 5, "container_runtime_log": 4}),
            NodeDef(name="worker-node-02", sensitivity=4, x=200, y=320, artifacts=["kubelet_logs", "cgroup_data"], artifact_decay={"kubelet_logs": 5, "cgroup_data": 4}),
            NodeDef(name="etcd-cluster", sensitivity=10, x=350, y=80, artifacts=["etcd_snapshot", "wal_logs", "memory_dump"], artifact_decay={"etcd_snapshot": 3, "wal_logs": 3, "memory_dump": 2}),
            NodeDef(name="coredns", sensitivity=3, x=350, y=200, artifacts=["dns_query_log"], artifact_decay={"dns_query_log": 7}),
            NodeDef(name="istio-mesh", sensitivity=6, x=350, y=340, artifacts=["envoy_access_log", "mtls_cert_chain"], artifact_decay={"envoy_access_log": 5, "mtls_cert_chain": 3}),
            NodeDef(name="vault-server", sensitivity=9, x=500, y=80, artifacts=["vault_audit", "seal_status_log"], artifact_decay={"vault_audit": 3, "seal_status_log": 4}),
            NodeDef(name="container-registry", sensitivity=5, x=500, y=200, artifacts=["pull_push_log", "image_signatures"], artifact_decay={"pull_push_log": 6, "image_signatures": 5}),
            NodeDef(name="prometheus", sensitivity=2, x=500, y=340, artifacts=["metric_snapshots"], artifact_decay={"metric_snapshots": 8}),
            NodeDef(name="ci-pipeline", sensitivity=5, x=620, y=80, artifacts=["pipeline_execution_log"], artifact_decay={"pipeline_execution_log": 6}),
            NodeDef(name="postgres-db", sensitivity=7, x=620, y=250, artifacts=["pg_stat_activity", "connection_log"], artifact_decay={"pg_stat_activity": 4, "connection_log": 5}),
            NodeDef(name="fluentd", sensitivity=1, x=80, y=400, artifacts=["log_pipeline_stats"], artifact_decay={"log_pipeline_stats": 10}),
        ],
        edges=[
            EdgeDef(source="k8s-api-server", target="worker-node-01"),
            EdgeDef(source="k8s-api-server", target="worker-node-02"),
            EdgeDef(source="k8s-api-server", target="etcd-cluster"),
            EdgeDef(source="worker-node-01", target="coredns"),
            EdgeDef(source="worker-node-02", target="istio-mesh"),
            EdgeDef(source="etcd-cluster", target="vault-server"),
            EdgeDef(source="coredns", target="container-registry"),
            EdgeDef(source="vault-server", target="ci-pipeline"),
            EdgeDef(source="istio-mesh", target="postgres-db"),
            EdgeDef(source="container-registry", target="postgres-db"),
            EdgeDef(source="worker-node-01", target="prometheus"),
            EdgeDef(source="k8s-api-server", target="fluentd"),
        ],
        attacker_path=[
            AttackerStep(step=1, action="probe", target="k8s-api-server"),
            AttackerStep(step=2, action="escalate", target="worker-node-01"),
            AttackerStep(step=3, action="lateral", target="worker-node-02"),
            AttackerStep(step=4, action="pivot", target="coredns"),
            AttackerStep(step=5, action="escalate", target="etcd-cluster"),
            AttackerStep(step=6, action="lateral", target="istio-mesh"),
            AttackerStep(step=7, action="pivot", target="vault-server"),
            AttackerStep(step=9, action="exfiltrate", target="etcd-cluster"),
        ],
    ),
    Scenario(
        id="shadow-hard-5", name="Financial SWIFT Network Breach", difficulty="hard",
        description="Attacker targets bank SWIFT terminal through compromised employee workstation. Multiple high-value targets, extremely fast movement. Based on Bangladesh Bank 2016 heist.",
        max_steps=12, honeypot_fidelity_start=0.72, critical_asset="swift-terminal",
        attack_source="Bangladesh Bank 2016 SWIFT Heist (Lazarus Group)",
        nodes=[
            NodeDef(name="employee-desktop", sensitivity=3, x=80, y=200, artifacts=["endpoint_telemetry", "browser_artifacts"], artifact_decay={"endpoint_telemetry": 5, "browser_artifacts": 4}),
            NodeDef(name="mail-gateway", sensitivity=4, x=80, y=350, artifacts=["email_filter_logs"], artifact_decay={"email_filter_logs": 7}),
            NodeDef(name="core-banking", sensitivity=8, x=230, y=80, artifacts=["transaction_audit", "session_logs"], artifact_decay={"transaction_audit": 4, "session_logs": 3}),
            NodeDef(name="treasury-system", sensitivity=9, x=230, y=200, artifacts=["wire_transfer_log", "approval_chain"], artifact_decay={"wire_transfer_log": 3, "approval_chain": 3}),
            NodeDef(name="swift-terminal", sensitivity=10, x=400, y=80, artifacts=["mt_message_log", "memory_dump", "operator_session_recording"], artifact_decay={"mt_message_log": 3, "memory_dump": 2, "operator_session_recording": 2}),
            NodeDef(name="swift-alliance", sensitivity=9, x=550, y=80, artifacts=["alliance_audit", "certificate_status"], artifact_decay={"alliance_audit": 3, "certificate_status": 3}),
            NodeDef(name="db-server", sensitivity=7, x=400, y=200, artifacts=["db_slow_query", "connection_pool_log"], artifact_decay={"db_slow_query": 5, "connection_pool_log": 4}),
            NodeDef(name="compliance-server", sensitivity=5, x=400, y=350, artifacts=["aml_screening_log"], artifact_decay={"aml_screening_log": 6}),
            NodeDef(name="print-server", sensitivity=2, x=550, y=200, artifacts=["print_confirmation_log"], artifact_decay={"print_confirmation_log": 8}),
            NodeDef(name="atm-controller", sensitivity=6, x=550, y=350, artifacts=["atm_transaction_log"], artifact_decay={"atm_transaction_log": 5}),
            NodeDef(name="hsm-module", sensitivity=8, x=230, y=350, artifacts=["key_usage_log", "signing_operations"], artifact_decay={"key_usage_log": 3, "signing_operations": 3}),
            NodeDef(name="security-ops", sensitivity=2, x=80, y=430, artifacts=["soc_ticket_log"], artifact_decay={"soc_ticket_log": 10}),
        ],
        edges=[
            EdgeDef(source="employee-desktop", target="core-banking"),
            EdgeDef(source="employee-desktop", target="treasury-system"),
            EdgeDef(source="employee-desktop", target="mail-gateway"),
            EdgeDef(source="core-banking", target="swift-terminal"),
            EdgeDef(source="treasury-system", target="swift-terminal"),
            EdgeDef(source="swift-terminal", target="swift-alliance"),
            EdgeDef(source="swift-terminal", target="db-server"),
            EdgeDef(source="treasury-system", target="hsm-module"),
            EdgeDef(source="db-server", target="compliance-server"),
            EdgeDef(source="swift-alliance", target="print-server"),
            EdgeDef(source="compliance-server", target="atm-controller"),
            EdgeDef(source="employee-desktop", target="security-ops"),
        ],
        attacker_path=[
            AttackerStep(step=1, action="probe", target="employee-desktop"),
            AttackerStep(step=2, action="escalate", target="core-banking"),
            AttackerStep(step=3, action="lateral", target="treasury-system"),
            AttackerStep(step=4, action="pivot", target="hsm-module"),
            AttackerStep(step=5, action="escalate", target="swift-terminal"),
            AttackerStep(step=6, action="lateral", target="db-server"),
            AttackerStep(step=7, action="pivot", target="swift-alliance"),
            AttackerStep(step=9, action="exfiltrate", target="swift-terminal"),
        ],
    ),
]

# All 15 scenarios
ALL_SCENARIOS: List[Scenario] = EASY_SCENARIOS + MEDIUM_SCENARIOS + HARD_SCENARIOS

# Task name → list of scenarios for that difficulty
TASK_SCENARIOS: Dict[str, List[Scenario]] = {
    "shadow-easy": EASY_SCENARIOS,
    "shadow-medium": MEDIUM_SCENARIOS,
    "shadow-hard": HARD_SCENARIOS,
}

# Quick lookup by scenario ID
SCENARIO_BY_ID: Dict[str, Scenario] = {s.id: s for s in ALL_SCENARIOS}

# Task metadata for /tasks endpoint
TASK_METADATA = [
    {
        "task_name": "shadow-easy",
        "description": "5-node network, slow attacker, obvious path. Learn observation and basic containment.",
        "difficulty": "easy",
        "max_steps": 20,
        "scenario_count": len(EASY_SCENARIOS),
    },
    {
        "task_name": "shadow-medium",
        "description": "8-node network, one decoy path, race conditions. Learn attacker modeling and sequencing.",
        "difficulty": "medium",
        "max_steps": 16,
        "scenario_count": len(MEDIUM_SCENARIOS),
    },
    {
        "task_name": "shadow-hard",
        "description": "12-node network, fast attacker, multiple pivot paths, 1 critical asset. Master stealth containment.",
        "difficulty": "hard",
        "max_steps": 12,
        "scenario_count": len(HARD_SCENARIOS),
    },
]


def get_scenario(task_name: str, scenario_index: int = 0) -> Scenario:
    """Get a specific scenario by task name and index."""
    scenarios = TASK_SCENARIOS.get(task_name)
    if not scenarios:
        raise ValueError(f"Unknown task: {task_name}. Valid: {list(TASK_SCENARIOS.keys())}")
    return scenarios[scenario_index % len(scenarios)]


def get_random_scenario(task_name: str, seed: int = None) -> Scenario:
    """Get a random scenario for the given task difficulty.

    Args:
        task_name: task difficulty key
        seed: if provided, seeds random before picking (for standalone use).
              When called from ShadowNetEnv.reset(seed=...) the RNG is already
              seeded upstream, so this arg can be omitted.
    """
    if seed is not None:
        random.seed(seed)
    scenarios = TASK_SCENARIOS.get(task_name)
    if not scenarios:
        raise ValueError(f"Unknown task: {task_name}")
    return random.choice(scenarios)
